name: Update ITV M3U

on:
  schedule:
    - cron: "0 */24 * * *" # 每小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update_itv_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download itv.m3u content
        run: curl -L -o itv.m3u https://s.wangqifei.eu.org/itv

      - name: Process itv.m3u
        run: |
          # Define input and output files
          input_file="itv.m3u"
          output_file="processed_itv.m3u"
          fps_file="fps.m3u8"
          hevc_file="hevc.m3u8"
          other_file="other.m3u8"

          # Clear temporary files and output file
          > "$output_file"

          # Get the current timestamp
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          {
            echo "# Last updated: $timestamp"
            echo "#EXTM3U"
            echo '#EXTM3U x-tvg-url="https://assets.livednow.com/epg.xml"'
            echo ""
          } > "$output_file"

          # Process HEVC entries
          awk -F'[ ,]' '/HEVC/ {print $0; getline; print $0; print ""}' "$input_file" >> "$output_file"

          # Process FPS entries
          awk -F'[ ,]' '/50 FPS/ {print $0; getline; print $0; print ""}' "$input_file" >> "$output_file"

          # Process regular entries (excluding HEVC and FPS)
          awk -F'[ ,]' '!/HEVC|50 FPS/ {print $0; print ""; getline; print $0}' "$input_file" >> "$output_file"

      - name: Stage changes
        run: |
          echo "Staging changes..."
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          mv processed_itv.m3u itv.m3u  # Replace the original file with the processed file
          git add itv.m3u

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update itv.m3u with timestamp"
          branch: main # Commit to the main branch
