name: Update ITV M3U

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update_itv_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download itv.m3u content
        run: curl -L -o itv.m3u https://s.wangqifei.eu.org/itv

      - name: Add timestamp comment
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          # Create a new file with the timestamp comment at the beginning
          echo "# Last updated: $timestamp" > itv_with_timestamp.m3u
          # Append the contents of the original file
          cat itv.m3u >> itv_with_timestamp.m3u

      - name: Process itv.m3u file
        run: |
          input_file="itv_with_timestamp.m3u"
          output_file="processed_itv.m3u"
          fps_file="fps.m3u8"
          hevc_file="hevc.m3u8"
          other_file="other.m3u8"

          # Clear temporary files and output file
          > "$output_file"
          > "$fps_file"
          > "$hevc_file"
          > "$other_file"

          # Read and retain the first line (timestamp comment) and the next two lines
          head -n 3 "$input_file" > "$output_file"

          # Process the remaining lines starting from the fourth line
          tail -n +4 "$input_file" | while IFS= read -r line; do
              if echo "$line" | grep -q 'tvg-name="[^"]*FPS"'; then
                  # If it contains FPS, adjust group-title attribute and append to FPS file
                  line=$(echo "$line" | sed -E 's/(group-title="[^"]*)"/\1FPS"/')
                  echo "$line" >> "$fps_file"
              elif echo "$line" | grep -q 'tvg-name="[^"]*HEVC"'; then
                  # If it contains HEVC, adjust group-title attribute and append to HEVC file
                  line=$(echo "$line" | sed -E 's/(group-title="[^"]*)"/\1HEVC"/')
                  echo "$line" >> "$hevc_file"
              else
                  # Other cases, write directly to other file
                  echo "$line" >> "$other_file"
              fi
          done

          # Merge the categorized files into the final output file
          cat "$hevc_file" "$fps_file" "$other_file" >> "$output_file"

          # Remove temporary files
          rm "$fps_file" "$hevc_file" "$other_file"

      - name: Stage changes
        run: |
          echo "Staging changes..."
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          mv processed_itv.m3u itv.m3u  # Replace the original file with the processed file
          git add itv.m3u

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update itv.m3u with timestamp"
          branch: main  # Commit to the main branch