name: process iptvhost

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  update_hosts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update DNS records and hosts file
      run: |
        # 定义 DNS 名称和对应的 host 文件内容
        DNS_NAMES=(
          'pixman.io.ystenlive.dnsany.com'
          'pixman.io.bestlive.dnsany.com'
          'pixman.io.wasulive.dnsany.com'
          'pixman.io.fifalive.dnsany.com'
          'pixman.io.hnbblive.dnsany.com'
        )

        HOSTS_MAPPING=(
          'cache.ott.ystenlive.itv.cmvideo.cn'
          'cache.ott.bestlive.itv.cmvideo.cn'
          'cache.ott.wasulive.itv.cmvideo.cn'
          'cache.ott.fifalive.itv.cmvideo.cn'
          'cache.ott.hnbblive.itv.cmvideo.cn'
        )

        # 清空之前的 iptvhost 文件
        > iptvhost

        # 解析 DNS 记录并更新 hosts 文件
        for i in "${!DNS_NAMES[@]}"; do
          dns_name="${DNS_NAMES[$i]}"
          host="${HOSTS_MAPPING[$i]}"

          # 递归解析 CNAME 记录到 IP 地址
          ip_address=$(dig +short "$dns_name" | head -n 1)

          while [[ "$ip_address" =~ ^[a-zA-Z0-9._-]+$ ]]; do
            echo "CNAME record found: $ip_address. Resolving further..."
            ip_address=$(dig +short "$ip_address" | head -n 1)
          done

          # 检查是否得到了 IP 地址
          if [ -n "$ip_address" ]; then
            echo "$ip_address $host" >> iptvhost
            echo "$ip_address $host"
          else
            echo "Failed to resolve $dns_name"
          fi
        done

    - name: Stage changes  # 步骤：暂存更改
      run: |
        echo "Staging changes..."  # 输出正在暂存更改的信息
        git config --global user.email "action@github.com"  # 配置全局用户邮箱
        git config --global user.name "GitHub Action"  # 配置全局用户名
        git add iptvhost  # 将转换后的文件添加到 Git 的暂存区
        git status  # 显示当前 Git 状态信息
    - name: Commit changes  # 步骤：提交更改
      uses: stefanzweifel/git-auto-commit-action@v4  # 使用 stefanzweifel/git-auto-commit-action 动作自动提交更改
      with:
        commit_message: Update iptvhost  # 提交消息为 Update iptvhost
        branch: main  # 提交到 main 分支
