name: Update IPTV Host

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  update_ip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      - name: Run update script
        run: |
          #!/bin/sh
          # 定义需要解析的域名和对应的缓存域名
          DOMAINS=(
              "pixman.io.ystenlive.dnsany.com"
              "pixman.io.bestlive.dnsany.com"
              "pixman.io.wasulive.dnsany.com"
              "pixman.io.fifalive.dnsany.com"
              "pixman.io.hnbblive.dnsany.com"
          )
          CACHE_DOMAINS=(
              "cache.ott.ystenlive.itv.cmvideo.cn"
              "cache.ott.bestlive.itv.cmvideo.cn"
              "cache.ott.wasulive.itv.cmvideo.cn"
              "cache.ott.fifalive.itv.cmvideo.cn"
              "cache.ott.hnbblive.itv.cmvideo.cn"
          )
          # 输出文件路径（仓库根目录下）
          OUTPUT_FILE="./iptvhost"
          # 清空文件内容
          : > "$OUTPUT_FILE"
          # 循环解析域名并写入文件
          for i in "${!DOMAINS[@]}"; do
              # 解析域名并提取IPv4地址
              nslookup_result=$(nslookup "${DOMAINS[$i]}" 2>/dev/null)
              
              # 删除前三行并提取 IPv4 地址
              IP=$(echo "$nslookup_result" | sed '1,3d' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
              
              # 检查IP是否为空
              if [ -n "$IP" ]; then
                  # 写入到文件中
                  echo "$IP ${CACHE_DOMAINS[$i]}" >> "$OUTPUT_FILE"
                  echo "Written to file: $IP ${CACHE_DOMAINS[$i]}"
              else
                  echo "No IPv4 address found for domain: ${DOMAINS[$i]}"
              fi
          done
          echo "itvDns已更新"

      - name: Stage changes
        run: |
          echo "Staging changes..."
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add iptvhost
          git status

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update iptvhost
          branch: sec  # 提交到 sec 分支
